services:
  - type: web
    name: erp-product-be
    runtime: java
    plan: starter
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/erp-product-be-1.0.0.jar
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
    autoDeploy: true
