services:
  - type: web
    name: erp-product-be
    env: docker
    plan: starter
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
    autoDeploy: true
