// ::: Code Generated by Copilot [b4f0548d-f80c-4d6f-9f53-f65fb6616845]. This comment will be removed automatically after the file is saved :::
package com.erp.service;

import com.erp.dto.*;
import com.erp.entity.InventoryCategory;
import com.erp.entity.InventoryItem;
import com.erp.entity.InventoryTransaction;
import com.erp.repository.InventoryCategoryRepository;
import com.erp.repository.InventoryItemRepository;
import com.erp.repository.InventoryTransactionRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Transactional
public class InventoryManagementService {
    
    private final InventoryItemRepository inventoryItemRepository;
    private final InventoryCategoryRepository categoryRepository;
    private final InventoryTransactionRepository transactionRepository;
    
    /**
     * Get inventory summary for dashboard
     */
    public InventorySummaryDTO getInventorySummary() {
        InventorySummaryDTO summary = new InventorySummaryDTO();
        
        List<InventoryItem> allItems = inventoryItemRepository.findAll();
        
        // Total items
        summary.setTotalItems(allItems.size());
        
        // Category counts
        summary.setDyesCount((int) allItems.stream()
                .filter(item -> item.getCategory() != null && item.getCategory().getName().contains("Dye"))
                .count());
        
        summary.setChemicalsCount((int) allItems.stream()
                .filter(item -> item.getCategory() != null && item.getCategory().getName().contains("Chemical"))
                .count());
        
        summary.setSolventsCount((int) allItems.stream()
                .filter(item -> item.getCategory() != null && item.getCategory().getName().contains("Solvent"))
                .count());
        
        // Total solvents on hand (in liters)
        BigDecimal totalSolvents = allItems.stream()
                .filter(item -> item.getCategory() != null && 
                        item.getCategory().getName().contains("Solvent") && 
                        "L".equalsIgnoreCase(item.getUnitOfMeasure()))
                .map(InventoryItem::getCurrentQuantity)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        summary.setTotalSolventsOnHand(totalSolvents);
        summary.setSolventsGrowthPercent(new BigDecimal("12.0")); // Mock growth percentage
        
        // Low stock items count
        summary.setLowStockItemsCount((int) allItems.stream()
                .filter(item -> "Low Stock".equals(item.getStockStatus()) || 
                               "Out of Stock".equals(item.getStockStatus()))
                .count());
        
        // Total inventory value
        BigDecimal totalValue = allItems.stream()
                .map(InventoryItem::getTotalValue)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        summary.setTotalInventoryValue(totalValue);
        
        // Last update cycle
        summary.setLastUpdateCycle("24h");
        
        // Storage capacity (mock calculation)
        summary.setStorageCapacityUsedPercent(new BigDecimal("72.0"));
        
        return summary;
    }
    
    /**
     * Get all inventory items with stock status
     */
    public List<InventoryItemDetailDTO> getAllInventoryItems() {
        return inventoryItemRepository.findAll().stream()
                .map(this::convertToDetailDTO)
                .collect(Collectors.toList());
    }

        // ::: Code Generated by Copilot [b4f0548d-f80c-4d6f-9f53-f65fb6616845]. This comment will be removed automatically after the file is saved :::
        /**
         * Get paginated inventory items with optional search and category filter
         */
        public InventoryItemsPageDTO getInventoryItemsPage(int page, int size, String search, String category) {
        int safePage = Math.max(page, 0);
        int safeSize = Math.max(size, 1);

        Page<InventoryItem> inventoryPage = inventoryItemRepository.searchInventoryItemsPaged(
            normalizeBlank(search),
            normalizeBlank(category),
            PageRequest.of(safePage, safeSize, Sort.by(Sort.Direction.DESC, "updatedAt"))
        );

        InventoryItemsPageDTO response = new InventoryItemsPageDTO();
        response.setContent(inventoryPage.getContent().stream()
            .map(this::convertToDetailDTO)
            .collect(Collectors.toList()));
        response.setPage(inventoryPage.getNumber());
        response.setSize(inventoryPage.getSize());
        response.setTotalElements(inventoryPage.getTotalElements());
        response.setTotalPages(inventoryPage.getTotalPages());
        response.setHasNext(inventoryPage.hasNext());
        response.setHasPrevious(inventoryPage.hasPrevious());
        return response;
        }

    /**
     * Get all inventory categories
     */
    public List<InventoryCategoryDTO> getInventoryCategories() {
        return categoryRepository.findAll().stream()
                .map(this::convertCategoryToDTO)
                .collect(Collectors.toList());
    }
    
    /**
     * Get inventory items by category
     */
    public List<InventoryItemDetailDTO> getInventoryItemsByCategory(String categoryName) {
        return inventoryItemRepository.findAll().stream()
                .filter(item -> item.getCategory() != null && 
                        item.getCategory().getName().equalsIgnoreCase(categoryName))
                .map(this::convertToDetailDTO)
                .collect(Collectors.toList());
    }
    
    /**
     * Get low stock items
     */
    public List<InventoryItemDetailDTO> getLowStockItems() {
        return inventoryItemRepository.findLowStockItems().stream()
                .map(this::convertToDetailDTO)
                .collect(Collectors.toList());
    }
    
    /**
     * Get inventory item detail by ID
     */
    public InventoryItemDetailDTO getInventoryItemDetail(Long id) {
        InventoryItem item = inventoryItemRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Inventory item not found with id: " + id));
        
        InventoryItemDetailDTO detailDTO = convertToDetailDTO(item);
        
        // Get recent transactions (last 10)
        List<InventoryTransaction> transactions = transactionRepository.findTop10ByInventoryItemIdOrderByTransactionDateDesc(id);
        detailDTO.setRecentTransactions(transactions.stream()
                .map(this::convertTransactionToDTO)
                .collect(Collectors.toList()));
        
        return detailDTO;
    }
    
    /**
     * Create new inventory item
     */
    public InventoryItemDetailDTO createInventoryItem(InventoryItemCreateDTO createDTO) {
        // Generate item code
        String itemCode = generateItemCode(createDTO.getType());
        
        InventoryItem item = new InventoryItem();
        item.setItemCode(itemCode);
        item.setName(createDTO.getItemName());
        item.setDescription(createDTO.getDescription());
        item.setUnitOfMeasure(createDTO.getUnit());
        item.setCurrentQuantity(createDTO.getOpeningStock());
        item.setUnitCost(createDTO.getCostPerUnit());
        item.setMinimumQuantity(createDTO.getLowStockThreshold());
        item.setReorderPoint(createDTO.getLowStockThreshold());
        item.setLowStockAlertsEnabled(createDTO.getLowStockAlertsEnabled());
        item.setLocation(createDTO.getLocation());
        item.setWeight(createDTO.getWeight());
        item.setWidth(createDTO.getWidth());
        item.setSupplier(createDTO.getSupplier());
        item.setIsActive(true);
        
        // Find or create category based on type
        InventoryCategory category = categoryRepository.findByName(createDTO.getType())
                .orElseGet(() -> {
                    InventoryCategory newCategory = new InventoryCategory();
                    newCategory.setName(createDTO.getType());
                    newCategory.setDescription(createDTO.getType() + " category");
                    newCategory.setIsActive(true);
                    return categoryRepository.save(newCategory);
                });
        item.setCategory(category);
        
        InventoryItem savedItem = inventoryItemRepository.save(item);
        
        // Create initial transaction for opening stock
        if (createDTO.getOpeningStock().compareTo(BigDecimal.ZERO) > 0) {
            createTransaction(savedItem, "ADJUSTMENT", createDTO.getOpeningStock(),
                    "Opening Stock", "Initial inventory", "STOCK_IN", "OPENING_STOCK", null, LocalDate.now());
        }
        
        return convertToDetailDTO(savedItem);
    }
    
    /**
     * Update inventory item
     */
    public InventoryItemDetailDTO updateInventoryItem(Long id, InventoryItemCreateDTO updateDTO) {
        InventoryItem item = inventoryItemRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Inventory item not found with id: " + id));
        
        item.setName(updateDTO.getItemName());
        item.setDescription(updateDTO.getDescription());
        item.setUnitOfMeasure(updateDTO.getUnit());
        item.setUnitCost(updateDTO.getCostPerUnit());
        item.setMinimumQuantity(updateDTO.getLowStockThreshold());
        item.setReorderPoint(updateDTO.getLowStockThreshold());
        item.setLowStockAlertsEnabled(updateDTO.getLowStockAlertsEnabled());
        item.setLocation(updateDTO.getLocation());
        item.setWeight(updateDTO.getWeight());
        item.setWidth(updateDTO.getWidth());
        item.setSupplier(updateDTO.getSupplier());
        
        // Update category if type changed
        if (updateDTO.getType() != null) {
            InventoryCategory category = categoryRepository.findByName(updateDTO.getType())
                    .orElseGet(() -> {
                        InventoryCategory newCategory = new InventoryCategory();
                        newCategory.setName(updateDTO.getType());
                        newCategory.setDescription(updateDTO.getType() + " category");
                        newCategory.setIsActive(true);
                        return categoryRepository.save(newCategory);
                    });
            item.setCategory(category);
        }
        
        InventoryItem updatedItem = inventoryItemRepository.save(item);
        return convertToDetailDTO(updatedItem);
    }
    

    /**
     * Adjust stock (Stock In / Stock Out)
     */
    public InventoryItemDetailDTO adjustStock(StockAdjustmentDTO adjustmentDTO) {
        InventoryItem item = inventoryItemRepository.findById(adjustmentDTO.getInventoryItemId())
                .orElseThrow(() -> new RuntimeException("Inventory item not found"));

        BigDecimal requestedQuantity = adjustmentDTO.getQuantity();
        BigDecimal movementQuantity = requestedQuantity.abs();
        if (movementQuantity.compareTo(BigDecimal.ZERO) == 0) {
            throw new RuntimeException("Quantity must be greater than zero");
        }

        String movementType = adjustmentDTO.getMovementType() == null
                ? ""
                : adjustmentDTO.getMovementType().trim().toUpperCase();

        BigDecimal transactionQuantity;

        // Movement type controls stock direction regardless of request quantity sign.
        if ("STOCK_IN".equals(movementType)) {
            item.setCurrentQuantity(item.getCurrentQuantity().add(movementQuantity));
            transactionQuantity = movementQuantity;
        } else if ("STOCK_OUT".equals(movementType)) {
            BigDecimal newQuantity = item.getCurrentQuantity().subtract(movementQuantity);
            if (newQuantity.compareTo(BigDecimal.ZERO) < 0) {
                throw new RuntimeException("Insufficient stock. Current: " + item.getCurrentQuantity() + 
                        ", Requested: " + movementQuantity);
            }
            item.setCurrentQuantity(newQuantity);
            transactionQuantity = movementQuantity.negate();
        } else {
            throw new RuntimeException("Invalid movement type. Use STOCK_IN or STOCK_OUT");
        }
        
        InventoryItem savedItem = inventoryItemRepository.save(item);
        
        // Create transaction
        String transactionType = mapReasonToTransactionType(adjustmentDTO.getReason());
        createTransaction(savedItem, transactionType, transactionQuantity,
                adjustmentDTO.getReason(), adjustmentDTO.getNotes(),
                movementType, adjustmentDTO.getLinkedOrderId(),
                adjustmentDTO.getReferenceId(), adjustmentDTO.getEffectiveDate());
        
        return convertToDetailDTO(savedItem);
    }
    
    /**
     * Get inventory transactions for an item
     */
    public List<InventoryTransactionDTO> getInventoryTransactions(Long inventoryItemId) {
        List<InventoryTransaction> transactions = transactionRepository
                .findByInventoryItemIdOrderByTransactionDateDesc(inventoryItemId);
        
        return transactions.stream()
                .map(this::convertTransactionToDTO)
                .collect(Collectors.toList());
    }
    
    /**
     * Get all recent inventory transactions (for transactions view)
     */
    public List<InventoryTransactionDTO> getAllRecentTransactions() {
        List<InventoryTransaction> transactions = transactionRepository
                .findTop50ByOrderByTransactionDateDesc();
        
        return transactions.stream()
                .map(this::convertTransactionToDTO)
                .collect(Collectors.toList());
    }

            // ::: Code Generated by Copilot [b4f0548d-f80c-4d6f-9f53-f65fb6616845]. This comment will be removed automatically after the file is saved :::
            /**
             * Get paginated recent inventory transactions with optional search and date range filter
             */
            public InventoryTransactionsPageDTO getRecentTransactionsPage(
                int page,
                int size,
                String search,
                LocalDate fromDate,
                LocalDate toDate) {

            int safePage = Math.max(page, 0);
            int safeSize = Math.max(size, 1);

            Page<InventoryTransaction> txPage = transactionRepository.searchRecentTransactions(
                normalizeBlank(search),
                fromDate,
                toDate,
                PageRequest.of(safePage, safeSize, Sort.by(Sort.Direction.DESC, "transactionDate").and(Sort.by(Sort.Direction.DESC, "createdAt")))
            );

            InventoryTransactionsPageDTO response = new InventoryTransactionsPageDTO();
            response.setContent(txPage.getContent().stream()
                .map(this::convertTransactionToDTO)
                .collect(Collectors.toList()));
            response.setPage(txPage.getNumber());
            response.setSize(txPage.getSize());
            response.setTotalElements(txPage.getTotalElements());
            response.setTotalPages(txPage.getTotalPages());
            response.setHasNext(txPage.hasNext());
            response.setHasPrevious(txPage.hasPrevious());
            return response;
            }
    
    /**
     * Delete inventory item
     */
    public void deleteInventoryItem(Long id) {
        InventoryItem item = inventoryItemRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Inventory item not found with id: " + id));
        
        // Soft delete - set to inactive
        item.setIsActive(false);
        inventoryItemRepository.save(item);
    }
    
    // ============ Helper Methods ============
    
    private InventoryItemDetailDTO convertToDetailDTO(InventoryItem item) {
        InventoryItemDetailDTO dto = new InventoryItemDetailDTO();
        dto.setId(item.getId());
        dto.setItemCode(item.getItemCode());
        dto.setName(item.getName());
        dto.setDescription(item.getDescription());
        dto.setCategoryId(item.getCategory() != null ? item.getCategory().getId() : null);
        dto.setCategoryName(item.getCategory() != null ? item.getCategory().getName() : null);
        dto.setCurrentStock(item.getCurrentQuantity());
        dto.setUnitOfMeasure(item.getUnitOfMeasure());
        dto.setUnitCost(item.getUnitCost());
        dto.setMinimumQuantity(item.getMinimumQuantity());
        dto.setReorderPoint(item.getReorderPoint());
        dto.setStockStatus(item.getStockStatus());
        dto.setIsActive(item.getIsActive());
        dto.setLocation(item.getLocation());
        dto.setWeight(item.getWeight());
        dto.setWidth(item.getWidth());
        dto.setSupplier(item.getSupplier());
        dto.setLowStockAlertsEnabled(item.getLowStockAlertsEnabled());
        dto.setTotalValue(item.getTotalValue());
        dto.setCreatedAt(item.getCreatedAt());
        dto.setUpdatedAt(item.getUpdatedAt());
        return dto;
    }

    private InventoryCategoryDTO convertCategoryToDTO(InventoryCategory category) {
        InventoryCategoryDTO dto = new InventoryCategoryDTO();
        dto.setId(category.getId());
        dto.setName(category.getName());
        dto.setDescription(category.getDescription());
        dto.setIsActive(category.getIsActive());
        dto.setCreatedAt(category.getCreatedAt());
        dto.setUpdatedAt(category.getUpdatedAt());
        return dto;
    }
    
    private InventoryTransactionDTO convertTransactionToDTO(InventoryTransaction transaction) {
        InventoryTransactionDTO dto = new InventoryTransactionDTO();
        dto.setId(transaction.getId());
        dto.setTransactionType(transaction.getTransactionType());
        dto.setInventoryItemId(transaction.getInventoryItem().getId());
        dto.setInventoryItemName(transaction.getInventoryItem().getName());
        dto.setReferenceNumber(transaction.getReferenceNumber());
        dto.setReferenceType(transaction.getReferenceType());
        dto.setReferenceId(transaction.getReferenceId());
        dto.setQuantity(transaction.getQuantity());
        dto.setUnitCost(transaction.getUnitCost());
        dto.setTotalCost(transaction.getTotalCost());
        dto.setBalanceAfter(transaction.getBalanceAfter());
        dto.setTransactionDate(transaction.getTransactionDate());
        dto.setNotes(transaction.getNotes());
        dto.setCreatedBy(transaction.getCreatedBy() != null ? transaction.getCreatedBy().getId() : null);
        dto.setCreatedByName(transaction.getCreatedBy() != null ? transaction.getCreatedBy().getUsername() : "System");
        dto.setCreatedAt(transaction.getCreatedAt());
        return dto;
    }
    

    private void createTransaction(InventoryItem item, String transactionType, BigDecimal quantity,
                                    String reason, String notes, String referenceType, String referenceNumber,
                                    Long referenceId, LocalDate transactionDate) {
        InventoryTransaction transaction = new InventoryTransaction();
        transaction.setInventoryItem(item);
        transaction.setTransactionType(transactionType);
        transaction.setQuantity(quantity);
        transaction.setUnitCost(item.getUnitCost());
        transaction.setTotalCost(quantity.multiply(item.getUnitCost()));
        transaction.setBalanceAfter(item.getCurrentQuantity());
        transaction.setTransactionDate(transactionDate != null ? transactionDate : LocalDate.now());
        transaction.setNotes(notes != null ? notes : reason);
        transaction.setReferenceType(referenceType);
        transaction.setReferenceNumber(referenceNumber);
        transaction.setReferenceId(referenceId);
        
        transactionRepository.save(transaction);
    }
    
    private String generateItemCode(String type) {
        String prefix;
        switch (type.toLowerCase()) {
            case "dye":
            case "dyes":
                prefix = "DYE";
                break;
            case "chemical":
            case "chemicals":
                prefix = "CHM";
                break;
            case "solvent":
            case "solvents":
                prefix = "SLV";
                break;
            case "auxiliary":
            case "auxiliaries":
                prefix = "AUX";
                break;
            case "raw material":
            case "raw materials":
                prefix = "RAW";
                break;
            default:
                prefix = "INV";
        }
        
        // Generate random 3-letter code + 3-digit number
        String randomCode = UUID.randomUUID().toString().substring(0, 3).toUpperCase();
        int randomNumber = (int) (Math.random() * 900) + 100;
        
        return prefix + "-" + randomCode + "-" + randomNumber;
    }
    
    private String mapReasonToTransactionType(String reason) {
        switch (reason.toLowerCase()) {
            case "purchase received":
            case "purchase order":
                return "PURCHASE";
            case "production usage":
            case "sample production":
                return "USAGE";
            case "customer return":
                return "RETURN";
            case "damage / wastage":
            case "damaged goods":
                return "ADJUSTMENT";
            case "inventory audit":
            case "manual adjustment":
                return "ADJUSTMENT";
            default:
                return "ADJUSTMENT";
        }
    }

    // ::: Code Generated by Copilot [b4f0548d-f80c-4d6f-9f53-f65fb6616845]. This comment will be removed automatically after the file is saved :::
    private String normalizeBlank(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }
}
