-- ::: Code Generated by Copilot [48f593be-5538-4fec-aad9-4269f601f0b9]. This comment will be removed automatically after the file is saved :::
DROP TABLE IF EXISTS inventory_adjustment_items;
DROP TABLE IF EXISTS inventory_adjustments;